# 1_Validate configuration check YAML syntax
# 2_Lint (super linter) Check many languages
# 3_test Run unit, integration, or API tests
# 4_build Compile the application
# 5_security check dependency, container, or secret scans
# 6_package check Create JAR, WAR, ZIP, or Docker image
# 7_publish check Upload artifacts or push Docker images
# 8_deploy check Deploy to Dev, QA, Staging, or Production
# 9_verify check moke tests, health checks, or end-to-end tests
# 10_clean up Remove temporary resources or old artifacts
---
stages:
  - lint
  - test
  - build
  - security
  - package
  - publish
  - deploy
  - verify
  - cleanup

cache:
  paths:
    - .m2/repository

lint:
  stage: lint
  image: pipelinecomponents/yamllint

  script:
    - yamllint .gitlab-ci.yml

test:
  stage: test
  image: maven:3.9.8-eclipse-temurin-21

  services:
    - name: postgres:16
      alias: postgres

  variables:
    POSTGRES_DB: Sokphorn_CRUD
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: st1998@1998@

  script:
    - sleep 10
    - mvn test

build:
  stage: build
  image: maven:3.9.8-eclipse-temurin-21

  script:
    - mvn -version
    - mvn clean package -DskipTests

  artifacts:
    when: always
    paths:
      - target/*.jar
    expire_in: 1 week

security:
  stage: security
  image: owasp/dependency-check

  script:
    - dependency-check.sh \
        --project "MonolithicCrud" \
        --scan .

package:
  stage: package

  image: docker:27

  services:
    - docker:27-dind

  variables:
    DOCKER_TLS_CERTDIR: ""

  script:
    - docker version
    - docker build -t monolithiccrud:v1 .

publish:
  stage: publish

  image: docker:27

  services:
    - docker:27-dind

  variables:
    DOCKER_TLS_CERTDIR: ""

  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest

deploy:
  stage: deploy

  image: docker:27

  services:
    - docker:27-dind

  variables:
    DOCKER_TLS_CERTDIR: ""

  script:
    - docker pull $CI_REGISTRY_IMAGE:latest

    - docker stop monolithiccrud || true
    - docker rm monolithiccrud || true

    - |
      docker run -d \
        --name monolithiccrud \
        -p 8080:8080 \
        $CI_REGISTRY_IMAGE:latest

verify:
  stage: verify
  image: docker:27

  services:
    - docker:27-dind

  variables:
    DOCKER_TLS_CERTDIR: ""

  script:
    - docker version
    - docker ps

cleanup:
  stage: cleanup

  script:
    - docker stop old-container || true
    - docker rm old-container || true
