name: CI Pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main


jobs:

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: YAML Lint
        uses: ibiqlik/action-yamllint@v3


  test:
    needs: lint

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16

        env:
          POSTGRES_DB: Sokphorn_CRUD
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: st1998@1998@

        ports:
          - 5432:5432

        options: >-
          --health-cmd="pg_isready -U postgres -d Sokphorn_CRUD"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5


    steps:

      - name: Checkout code
        uses: actions/checkout@v4


      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven


      - name: Run tests
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/Sokphorn_CRUD
          SPRING_DATASOURCE_USERNAME: postgres
          SPRING_DATASOURCE_PASSWORD: st1998@1998@

        run: mvn test
