name: Java Spring Boot CI/CD

on:
  push:
    branches:
      - main

  pull_request:

env:
  IMAGE_NAME: monolithiccrud

jobs:

  ##################################
  # LINT
  ##################################
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install yamllint
        run: |
          sudo apt update
          sudo apt install yamllint -y

      - name: Lint YAML
        run: yamllint .github/workflows/ci-cd.yml

  ##################################
  # TEST
  ##################################
  test:
    needs: lint

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16

        env:
          POSTGRES_DB: Sokphorn_CRUD
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: st1998@1998@

        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Run Test
        run: mvn test

  ##################################
  # BUILD
  ##################################
  build:
    needs: test

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Build
        run: mvn clean package -DskipTests

      - uses: actions/upload-artifact@v4
        with:
          name: springboot-jar
          path: target/*.jar

  ##################################
  # SECURITY
  ##################################
  security:
    needs: build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: MonolithicCrud
          path: .

  ##################################
  # PACKAGE
  ##################################
  package:
    needs: security

    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t $IMAGE_NAME:v1 .

  ##################################
  # PUBLISH
  ##################################
  publish:
    needs: package

    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" \
          | docker login ghcr.io \
            -u ${{ github.actor }} \
            --password-stdin

      - name: Build Image
        run: |
          docker build \
          -t ghcr.io/${{ github.repository }}/monolithiccrud:latest .

      - name: Push Image
        run: |
          docker push \
          ghcr.io/${{ github.repository }}/monolithiccrud:latest

  ##################################
  # DEPLOY
  ##################################
  deploy:
    needs: publish

    runs-on: self-hosted

    steps:
      - name: Pull Image
        run: |
          docker pull \
          ghcr.io/${{ github.repository }}/monolithiccrud:latest

      - name: Stop Old Container
        run: |
          docker stop monolithiccrud || true
          docker rm monolithiccrud || true

      - name: Run Container
        run: |
          docker run -d \
            --name monolithiccrud \
            -p 8080:8080 \
            ghcr.io/${{ github.repository }}/monolithiccrud:latest

  ##################################
  # VERIFY
  ##################################
  verify:
    needs: deploy

    runs-on: self-hosted

    steps:
      - name: Docker Containers
        run: docker ps

      - name: Health Check
        run: curl http://localhost:8080/actuator/health

  ##################################
  # CLEANUP
  ##################################
  cleanup:
    needs: verify

    runs-on: self-hosted

    if: always()

    steps:
      - name: Cleanup
        run: |
          docker stop old-container || true
          docker rm old-container || true
